# $FreeBSD

MASTERDIR=	${.CURDIR}/../../sysutils/openzfs-KMOD

.include	"${MASTERDIR}/Makefile"

CATEGORIES=	remos sysutils
PKGNAMESUFFIX?=	-kmod-remos

MAINTAINER=	darkfiberiru@remos.dev
KMODTARGET?=	openzfs-remos.ko


